#!/usr/bin/env zsh

# https://github.com/zdharma/zplugin
source ~/.zplugin/bin/zplugin.zsh

for config in ~/.zshrc.d/plugins/*.sh; do
  source $config
done

# Load completions
autoload -Uz compinit
compinit
