#!/usr/bin/env zsh

# https://github.com/zdharma/zinit
source ~/.zinit/bin/zinit.zsh

for config in ~/.zshrc.d/plugins/*.sh; do
  source $config
done

# Load completions
autoload -Uz compinit
compinit
